# Generated by Django 6.0.5 on 2026-05-18 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_fournisseur_produit_fournisseur_mouvementstock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fournisseur',
            options={'verbose_name_plural': 'Fournisseurs'},
        ),
        migrations.AlterModelOptions(
            name='mouvementstock',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Mouvements de stock'},
        ),
    ]
